### ISSUE TITLE
Windir error

### ISSUE THREAD

**Issue by itineric** [mossc001/Bresser-Weather-Station#2]
Difference between line 191 and 254. Not working out of the box.
Why did you change the key ?

**Comment by mossc001** [comment]
> Difference between line 191 and 254. Not working out of the box.
> 
> Why did you change the key ?

Let me check. I updated the YAML because the old sensor type is deprecated in Home Assistant.

**Comment by mossc001** [comment]
@itineric , really sorry, I made a modification a while ago for wind direction in degrees rather than cardinal. I commented out the cardinal but have now made it a bit clearer in the code as to which you can use (or both):

`// Use this WindDir if you want wind direction as per a compass
$mqtt->publish($mqttRoot .'winddir',wind_cardinal( $_GET["winddir"]), 0);

// Use this WindDir if you want wind direction in degrees
$mqtt->publish($mqttRoot .'winddirection', $_GET["winddir"], 0);`

Let me know if this fixes it and I'll close the issue?

**Comment by itineric** [comment]
yes, it works, thx
